# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49549f3150de1ac7b6a085a867f86227306cdb63b3ddeb5333d3b2ce5c293894fa08dc05afca9ca15d83af66d544a2f81991e9c981bb340830d87f0861d65c09

test:
  secret_key_base: 1e1c1470015cbadfe9a7a7fbd67d6804edc5d68454c3a2315891ece02ed68e76975df5d19ddadac889555213e3117efe63ad762dfaa27dd112ba17886e5e2eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
